config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  # devise_for :users
  root 'home#index'
  devise_for :users, controllers: {
        sessions: 'users/sessions'
  }

  namespace :admin do
	  get 'dashboard/index'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
	layout 'admin'
	def index

	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user.present?
  		if current_user.role == 1
  			redirect_to admin_dashboard_index_path
  		end
  	end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    self.resource = resource_class.new(sign_in_params)
    clean_up_passwords(resource)
    yield resource if block_given?
    respond_with(resource, serialize_options(resource))
  end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    # respond_with resource, location: after_sign_in_path_for(resource)
    flash[:success] = "Successfully login!"
    redirect_to root_path
  end

  # DELETE /resource/sign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?
    # respond_to_on_destroy
    redirect_to root_path
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/dashboard/index.html.erb
<div class="container">
  <br>
   <div class="row">
      <div class="col s3 teal">
        <span><i class="large material-icons white-text">recent_actors</i></span>
      </div>
      <div class="col s3 ">2</div>
      
    </div>
  <br>
</div>

app/views/admin/includes/_footer.html.erb
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= javascript_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script type="text/javascript">
	// $(document).ready(()=> alert("working") );

	// $(".dropdown-trigger").dropdown();
      
   //    document.addEventListener('DOMContentLoaded', function() {
	  //   var elems = document.querySelectorAll('.carousel');
	  //   var instances = M.Carousel.init(elems, options);
	  // });

	  // Or with jQuery

	  $(document).ready(function(){
	    // $('.carousel').carousel();
      $('.tooltipped').tooltip();
	  });


	  // Or with jQuery

	  // $('.carousel.carousel-slider').carousel({
	  //   fullWidth: true,
	  //   indicators: true
	  // });
	  // $(document).ready(function(){
	  //   $('.parallax').parallax();
	  // });


	  // sidenav
	    $(document).ready(function(){
		    $('.sidenav').sidenav();
		  });
        

    // toaste
          	 
   
    <% unless flash.empty? %>
     <% flash.each do |f| %>
        <% type = f[0].to_s %>
        Swal.fire({
          position: 'top-end',
          icon: '<%= type %>',
          title: '<%= f[1] %>',
          showConfirmButton: true,
          timer: 1500
        });
       <% end %>
     <% end %>
</script>	

app/views/admin/includes/_header.html.erb
 <div class="navbar-fixed">
  <nav> <!-- navbar content here  --> </nav>

  <ul id="slide-out" class="sidenav">
    <li><div class="user-view">
      <div class="background">
        <%= image_tag "two.png"  %>
      </div>
      <a href="#user"><%= image_tag "t1.jpg" ,class: "circle" %> </a>
      <!-- <a href="#name"><span class="white-text name">John Doe</span></a> -->
      <a href="#email"><span class="white-text email"><%= current_user.email %></span></a>
      <a href="<%= destroy_user_session_path %>" data-method="delete" >Logout</a>
    </div></li>
    <li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
    <li><a href="#!">Second Link</a></li>
    <li><div class="divider"></div></li>
    <li><a class="subheader">Subheader</a></li>
    <li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
  </ul>
  
       
</div>
<a href="#" data-target="slide-out" class="sidenav-trigger menu" ><i class="material-icons">menu</i></a>

app/views/home/index.html.erb
<!-- <div class="carousel">
    <a class="carousel-item" href="#one!"><%= image_tag "one.png" %></a>
    <a class="carousel-item" href="#two!"><%= image_tag "two.png" %></a>
    <a class="carousel-item" href="#three!"><%= image_tag "three.png" %></a>
    <a class="carousel-item" href="#four!"><%= image_tag "four.png" %></a>
    <a class="carousel-item" href="#five!"><%= image_tag "five.png" %></a>
</div>  -->
<!--       
<div class="container">
	<h1>Home#index</h1>
	<p class="z-depth-5 flow-text" >Find me in app/views/home/index.html.erb</p>

  <div class="card-panel hoverable"><a class="btn-floating btn-large cyan pulse"><i class="material-icons">edit</i></a> &nbsp; Hoverable Card Panel</div>
        <blockquote>
      This is an example quotation that uses the blockquote tag.
    </blockquote>
</div> -->

<div class="container head" align="center">
	<br>
	<h1><b><span style="color: gray;font-family: 'Balsamiq Sans', cursive;" >I Write</span> <span style="color: green;font-family: 'Balsamiq Sans', cursive;">Code</span></b></h1>
	<!-- <hr> -->
</div>
<!--   <div class="carousel carousel-slider">
    <a class="carousel-item" href="#one!"><%= image_tag "one.png" %></a>
    <a class="carousel-item" href="#two!"><%= image_tag "two.png" %></a>
    <a class="carousel-item" href="#three!"><%= image_tag "three.png" %></a>
    <a class="carousel-item" href="#four!"><%= image_tag "four.png" %></a>
  </div> -->

  	<div class="parallax-container">
      <div class="parallax"><%= image_tag "three.png" %></div>
    </div>
    <div class="section khaki" align="center" >
      <h2 class="header">Merchendies</h2>
      <div class="row container">
        <div class="carousel">
		    <a class="carousel-item" href="#one!"><%= image_tag "t1.jpg" %></a>
		    <a class="carousel-item" href="#two!"><%= image_tag "t2.jpg" %></a>
		    <a class="carousel-item" href="#three!"><%= image_tag "t3.jpg" %></a>
		    <a class="carousel-item" href="#four!"><%= image_tag "t4.jpg" %></a>
		    <a class="carousel-item" href="#five!"><%= image_tag "t5.jpg" %></a>
		</div>
      </div>
    </div>
    <div class="parallax-container">
      <div class="parallax"><%= image_tag "one.png"%></div>
    </div>
    <div class="section khaki">
      <div class="row container">
        <div class="col s4" >
          <%= image_tag "t1.jpg",class:"responsive-img"  %>
        </div>
        <div class="col s8">
          <h2 class="header">Parallax</h2>
          <p class="grey-text text-darken-3 lighten-3">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
      </div>
    </div>
    <div class="parallax-container">
      <div class="parallax"><%= image_tag "four.png" %></div>
	</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>


<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= javascript_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script type="text/javascript">
	// $(document).ready(()=> alert("working") );

	$(".dropdown-trigger").dropdown();
      
   //    document.addEventListener('DOMContentLoaded', function() {
	  //   var elems = document.querySelectorAll('.carousel');
	  //   var instances = M.Carousel.init(elems, options);
	  // });

	  // Or with jQuery

	  $(document).ready(function(){
	    $('.carousel').carousel();
      $('.tooltipped').tooltip();
	  });


	  // Or with jQuery

	  $('.carousel.carousel-slider').carousel({
	    fullWidth: true,
	    indicators: true
	  });
	  $(document).ready(function(){
	    $('.parallax').parallax();
	  });


    // toaste
           
   
    <% unless flash.empty? %>
     <% flash.each do |f| %>
        <% type = f[0].to_s %>
        Swal.fire({
          position: 'top-end',
          icon: '<%= type %>',
          title: '<%= f[1] %>',
          showConfirmButton: true,
          timer: 1500
        });
       <% end %>
     <% end %>
</script>	

app/views/layouts/_header.html.erb
<div class="navbar-fixed">
 <nav class="nav-extended">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">LCO</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        <li><a href="<%=  products_index_path() %>">Products</a></li>
        <% if !current_user.present?  %>
            <li><a href="<%= new_user_session_path %>">Login</a></li>
        <% else %>
            <li><a href="<%= destroy_user_session_path %>" data-method="delete" >Logout</a></li>
        <% end %>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
      <ul id="dropdown1" class="dropdown-content">
        <li><a href="#!">one</a></li>
        <li><a href="#!">two</a></li>
        <li class="divider"></li>
        <li><a href="#!">three</a></li>
      </ul>
    </div>
    <!-- <div class="nav-content">
      <ul class="tabs tabs-transparent">
        <li class="tab"><a href="#test1">Test 1</a></li>
        <li class="tab"><a class="active" href="#test2">Test 2</a></li>
        <li class="tab disabled"><a href="#test3">Disabled Tab</a></li>
        <li class="tab"><a href="#test4">Test 4</a></li>
      </ul>
    </div> -->
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><a href="sass.html">Sass</a></li>
    <li><a href="badges.html">Components</a></li>
    <li><a href="collapsible.html">JavaScript</a></li>
  </ul>

</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <%= render 'admin/includes/header' %>
    <%= yield %>
  </body>
    <%= render 'admin/includes/footer' %>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
    <%= render 'layouts/footer' %>
</html>

app/views/products/index.html.erb
<div class="container">
	<div class="row">
	    <div class="col s12 m4">
	      <div class="card">
	        <div class="card-image">
	          <!-- <img src="images/sample-1.jpg"> -->
	          <%= image_tag "one.png" %>
	          <span class="card-title">Card Title</span>
	          <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add</i></a>
	        </div>
	        <div class="card-content">
	          <p>I am a very simple card. I am good at containing small bits of information.
	          I am convenient because I require little markup to use effectively.</p>
	        </div>
	        <div class="card-action">
	          <a href="#">This is a link</a>
	        </div>
	      </div>
	    </div>


	    <div class="col s12 m4">
	      <div class="card">
	        <div class="card-image">
	          <!-- <img src="images/sample-1.jpg"> -->
	          <%= image_tag "one.png" %>
	          <span class="card-title">Card Title</span>
	          <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add</i></a>
	        </div>
	        <div class="card-content">
	          <p>I am a very simple card. I am good at containing small bits of information.
	          I am convenient because I require little markup to use effectively.</p>
	        </div>
	        <div class="card-action">
	          <a href="#">This is a link</a>
	        </div>
	      </div>
	    </div>


	    <div class="col s12 m4">
	      <div class="card">
	        <div class="card-image">
	          <!-- <img src="images/sample-1.jpg"> -->
	          <%= image_tag "one.png" %>
	          <span class="card-title">Card Title</span>
	          <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add</i></a>
	        </div>
	        <div class="card-content">
	          <p>I am a very simple card. I am good at containing small bits of information.
	          I am convenient because I require little markup to use effectively.</p>
	        </div>
	        <div class="card-action">
	          <a href="#">This is a link</a>
	        </div>
	      </div>
	    </div>


	    <div class="col s12 m4">
	      <div class="card">
	        <div class="card-image">
	          <!-- <img src="images/sample-1.jpg"> -->
	          <%= image_tag "one.png" %>
	          <span class="card-title">Card Title</span>
	          <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add</i></a>
	        </div>
	        <div class="card-content">
	          <p>I am a very simple card. I am good at containing small bits of information.
	          I am convenient because I require little markup to use effectively.</p>
	        </div>
	        <div class="card-action">
	          <a href="#">This is a link</a>
	        </div>
	      </div>
	    </div>


	    <div class="col s12 m4">
	      <div class="card">
	        <div class="card-image">
	          <!-- <img src="images/sample-1.jpg"> -->
	          <%= image_tag "one.png" %>
	          <span class="card-title">Card Title</span>
	          <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add</i></a>
	        </div>
	        <div class="card-content">
	          <p>I am a very simple card. I am good at containing small bits of information.
	          I am convenient because I require little markup to use effectively.</p>
	        </div>
	        <div class="card-action">
	          <a href="#">This is a link</a>
	        </div>
	      </div>
	    </div>
  </div>
</div>